name: ğŸ Build iOS Archive

on:
  push:
    branches:
      - main2
#      - feature/**
#  pull_request:
#    types: [closed]
#    branches:
#      - main2
#      - feature/**
  workflow_dispatch:

jobs:
  build-ios:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: macos-14

    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: ğŸ’¾ Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: ğŸ’¾ Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: konan-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: konan-${{ runner.os }}-

      - name: ğŸ§° Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: ğŸ§¼ Clean previous build
        run: ./gradlew clean --no-daemon

      - name: ğŸ› ï¸ Build shared module (KMM - iOS only)
        run: ./gradlew :composeApp:linkReleaseFrameworkIosArm64 --build-cache --parallel --no-daemon

      - name: ğŸ§± Build iOS App (archive)
        run: |
          cd iosApp
          xcodebuild archive \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: ğŸ“¤ Upload iOS Archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-archive
          path: iosApp/build/iosApp.xcarchive
